services:
  - name: backend
    type: web
    buildCommand: |
      cd backend
      npm install
      npm run dev

  - name: frontend
    type: web
    buildCommand: |
      cd frontend
      npm install
      npm run start
