services:
  - name: backend
    type: web
    buildCommand: npm run build
    startCommand: cd backend && npm run dev
    env:
      - key: NODE_ENV
        value: production
  - name: frontend
    type: web
    buildCommand: npm run build
    startCommand: cd frontend && npm start
